array_width = 30
color = "Always"
error_on_line_overflow = true
error_on_unformatted = true
fn_params_layout = "Vertical"
format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
single_line_if_else_max_width = 100
single_line_let_else_max_width = 100
wrap_comments = true
